name: TABLE22PROJECTS
favicon: null
layout_spectrum: 0.49101
typography_spectrum: 0.67304
title: TABLE22PROJECTS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d634a'
    - '#f66502'
    - '#ffffff'
    - '#93a192'
    - '#f6f7f6'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
