name: TABLE22PROJECTS
favicon: null
layout_spectrum: 0.12067457847297192
typography_spectrum: 0.09113130439072847
title: TABLE22PROJECTS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.16970170265994966
  lightness: 0.8254788969643414
  saturation: 0.8600901958998293
  rhythmicContrast: 0.4154240528587252
purpose: []
