title: TABLE22PROJECTS
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Producing Films from Pages to Screens
color:
  saturation: 0.103652
  brandStrength: 0.4736199507024139
  lightness: 1
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  rhythmicContrast: 0.4054779
cta:
  bucket: null
  version: null
  domain: null
name: TABLE22PROJECTS
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4387755
layout_spectrum: 0.03598281
