name: TABLE22PROJECTS
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5427
title: TABLE22PROJECTS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4d634a'
    - '#f66502'
    - '#3a5336'
    - '#4c6548'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
