typography_spectrum: 0.5427
color:
  brandColors:
    - '#ffffff'
    - '#4d634a'
    - '#f66502'
    - '#3a5336'
    - '#4c6548'
  brandStrength: 1
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.26067
analytics:
  google: null
  facebook: null
  twitter: null
name: TABLE22PROJECTS
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: TABLE22PROJECTS
description: Producing Films from Pages to Screens
purpose: []
